version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuContraseñaFuerte!2023
    ports:
      - "1433:1433"

  servicio-productos:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=123
      - DB_SERVER=DESKTOP-5H4JARL\CAROLINA
      - DB_DATABASE=Distribuidas
      - PORT=3000
    depends_on:
      - sqlserver
